### ISSUE TITLE
No Background After Manual Installation of Spicetify Galaxy

### ISSUE THREAD

**Issue by Goodly58** [harbassan/spicetify-galaxy#1]
Spicetify version: 2.14.1
Installed spicetify-galaxy using git clone in the themes folder, tried manually installing [Retroblur](https://github.com/Motschen/Retroblur) to test, and it worked fine. Spicetify-galaxy has backgrounds for playlists and albums when installed using Marketplace. I installed it manually because the marketplace has an issue with the background, an [issue Retroblur has](https://github.com/Motschen/Retroblur/issues/7) too, which doesn't happen (at least as tested with Retroblur), if installed directly from GitHub.
![image](https://user-images.githubusercontent.com/63460148/202855454-30487562-11ec-4868-bdb4-f1e2956ee2c3.png)
This is what I see after manually installing the theme:
Playlists:
![image](https://user-images.githubusercontent.com/63460148/202855527-eacd8ee6-288e-409f-9d57-66928fe2e6cc.png)
Albums:
![image](https://user-images.githubusercontent.com/63460148/202855565-d37cb664-6d8a-4273-b17c-b2da37e179a3.png)

**Comment by harbassan** [comment]
That issue you were having with the marketplace version should be fixed now. Let me know if there's still some sort of issue occurring.

**Comment by harbassan** [comment]
Also, when you manually installed the theme did you add galaxy.js to the extensions in your config file? If not that is likely the issue with the manual install.

**Comment by Goodly58** [comment]
Marketplace version is fixed! I also put galaxy.js in the extensions folder as per your comment and applied the command "spicetify config extensions galaxy.js" and manual installation works too now! I just wanted to say I'm a huge fan of this theme, from the spotify player at the bottom to playlist title and description position, and everything in between. Thank you for your help and fixing the marketplace issue.
