### ISSUE TITLE
The Home button is broken

### ISSUE THREAD

**Issue by NotROSES** [harbassan/spicetify-galaxy#10]
Hello, I just installed the galaxy theme today but the home button is broken it's upside and I can't click it. I hope you'll be able to fix it. since I installed spicetify it's my favorite. this is an ss. https://oxyroses.discowd.com/Spotify_lpUcbdFiof.png

**Comment by harbassan** [comment]
what are your spotify and spicetify versions? You can check by clicking on the three dots > help > about spotify. If its not up to date that might be the reason for the issue. If that doesnt work screenshot your config file and send it here.

**Comment by NotROSES** [comment]
spotify:1.2.3.115
spicetify: v2.16.0

**Comment by harbassan** [comment]
ss your config.ini file and send it.

**Comment by NotROSES** [comment]
https://oxyroses.discowd.com/notepad_Kl4xCfME5g.png

**Comment by harbassan** [comment]
go into your spicetify folder and the file should be config-xpui.ini. send me that.

**Comment by NotROSES** [comment]
https://oxyroses.discowd.com/notepad_Z7sSglgKcs.png

**Comment by harbassan** [comment]
yeah remove dribbblish.js from the  extensions list.

**Comment by NotROSES** [comment]
yes working. thank you so much. its my favorite theme ever.

**Comment by harbassan** [comment]
sweet
