### ISSUE TITLE
[Suggestion] blur

### ISSUE THREAD

**Issue by Sooperfish** [harbassan/spicetify-galaxy#11]
I'm using the 'use currently playing song as home bg' option and it would be sweet with some blur. Maybe in combination with not hiding the original album art if the rest is gonna be blurred, or only having blur in the home menu.

Love the theme!

**Comment by harbassan** [comment]
Yeah i'll get on this for you. Might add a couple of different options for toggling home and other pages seperately, seems like a good idea.

**Comment by Sooperfish** [comment]
Good luck!

**Comment by harbassan** [comment]
Once it updates the new options should be working. Let me know if you have any other issues/suggestions.

**Comment by Sooperfish** [comment]
Thanks! Looks really good at a really high set blur to give it that windows 11 blur look
