### ISSUE TITLE
No fullscreen background for playlists

### ISSUE THREAD

**Issue by AarshGajjar** [harbassan/spicetify-galaxy#12]
The full screen background for current playing song and the artist page works fine but does not change on opening a playlist like it used to before. 

Spotify for Windows
1.2.4.912.g949d5fd0
Spicetify v2.16.1

**Comment by harbassan** [comment]
could you screenshot exactly what it looks like?

**Comment by AarshGajjar** [comment]
The current playing tracks, artist and album page have backgrounds but the background does not change when a playlist page is opened to show the playlist cover, instead whatever the last background was, is shown.

track background: 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/60134947/217784421-084de5b6-23fa-4dc9-97a7-94eb00e90541.png">

artist background: 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/60134947/217784515-d62876c5-f5ec-4302-8b6a-38d11f6fb81c.png">

album background:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/60134947/217784918-9ba4ea5c-e090-4c8c-8767-9a3100250be8.png">

playlist background: 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/60134947/217785393-193b8d83-ffde-420b-97c4-e8d67f32c8d5.png">

**Comment by harbassan** [comment]
can you go into devtools and check if there are any errors showing in the log?

**Comment by AarshGajjar** [comment]
how do i do that?

**Comment by AarshGajjar** [comment]
There seems to be some problem with the playlist page, becase when a playlist page is open, the current track background also stops changing.

**Comment by harbassan** [comment]
ok, so if you monitor the console directly after opening Spotify, does this error message show up exactly at the instant when you open any playlist page?

**Comment by AarshGajjar** [comment]
on startup:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/60134947/218237975-21827615-f081-4552-bed5-c9b5d1ba164a.png">


this is the error i get now when i open a playlist page:

<img width="959" alt="image" src="https://user-images.githubusercontent.com/60134947/218237911-c8290168-0275-4ced-906d-b4b02ba3bb72.png">

**Comment by harbassan** [comment]
should be working once it updates on marketplace

**Comment by AarshGajjar** [comment]
<img width="944" alt="image" src="https://user-images.githubusercontent.com/60134947/218244156-923d711a-fabd-4d05-9bb0-d89e9b5c77e7.png">

**Comment by AarshGajjar** [comment]
Thank you!
