### ISSUE TITLE
Something went wrong error 

### ISSUE THREAD

**Issue by ahmed-tito** [harbassan/spicetify-galaxy#14]
When I open an artist page it gives me this error a lot it seems random, but it doesn't happen when I'm playing the song of that artist, based on that I found a "fix"where I have to play an artist's song so that I can open his page. my settings are use the current song as bg and use home bg everywhere, I wonder if there was an option to allow home bg everywhere even on artists pages would be a temporary fix 
my spicetify v2.16.1 and I installed through the marketplace.
![image](https://user-images.githubusercontent.com/80455029/218758699-f51f6f15-d4a3-4efc-b6ce-9ae094e6e008.png)
I wanna say I love this project so much, It's my favourite Theme/addition to the app

**Comment by harbassan** [comment]
Could you enable the dev-tools and then send a screenshot of the console when the error happens. To enable the devtools run the command: spicetify enable-devtools.

**Comment by JKnow27** [comment]
Hi! I'm Having the same issue, when I try to enable devtools it gave me this error 

![image](https://user-images.githubusercontent.com/125528668/219260623-35f4004f-2278-4e07-a975-6c06b9917d79.png)

**Comment by harbassan** [comment]
without the full stop sorry

**Comment by JKnow27** [comment]
oh. Yeah i also didn't notice that

Ummmm
![image](https://user-images.githubusercontent.com/125528668/219267638-83315721-7723-4636-8858-37f6591e941d.png)

**Comment by JKnow27** [comment]
This happens both while installing the theme trought powershell and trough the integrated marketplace in spicetify

**Comment by harbassan** [comment]
Does the same thing happen on other themes?

**Comment by JKnow27** [comment]
Nope
at least not with the ones I've tried, like 3 or 4 other from the marketplace

**Comment by harbassan** [comment]
What version of spotify are you on? I think the problem might actually be related to the most recent spotify update, because I can see a lot of other people having the error aswell.

**Comment by JKnow27** [comment]
Yeah, i'm using the latest version
I had the theme installed before (with no issues) but had to wipe my ssd, so i'm on a clean windows install. The issue happened when I installed everything with a fresh spotify install.

**Comment by harbassan** [comment]
version 1.24 or 1.2.5?

**Comment by n0ia96** [comment]
> version 1.24 or 1.2.5?

Spotify for Windows
1.2.4.912.g949d5fd0
Spicetify v2.16.1

**Comment by harbassan** [comment]
Ok the only solution I have right now is to go back to a previous version of spotify, or it might just get fixed in 1.2.5 whenever that releases for you.

**Comment by ahmed-tito** [comment]
![image](https://user-images.githubusercontent.com/80455029/219864819-a94508b1-ebdb-42ba-91b7-1b0e6d57b123.png)

Okay this what shows up when that happens 

also i found out that when you adjust the window size of Spotify this issue completely disappears and if im on a page that is woring properly the second i change the window size it breaks

**Comment by ahmed-tito** [comment]
I recorded a video of the whole error
https://youtu.be/ExKPIPpN0G0

**Comment by harbassan** [comment]
still experiencing the issue?

**Comment by Fumi8481** [comment]
I also have the same issue right now are there any fixes?

**Comment by opensource0apps0enthusiast** [comment]
Having the same issue here. Version and other info:
Spotify for Windows
1.2.6.863.ge7902f05
Spicetify v2.16.2
Theme: Galaxy / base
Extensions: adblock.js, galaxy.js
Custom apps: marketplace

**Comment by mazenR** [comment]
i have the same, problem how can i go back to a previous version of Spotify

**Comment by harbassan** [comment]
I've updated the theme so check if the latest version is working without the error (might take a few hours to update on the marketplace).

**Comment by gheorghe-zalinschi** [comment]
still same issues on my spotify

**Comment by gheorghe-zalinschi** [comment]
on the search bar

**Comment by ultrangels** [comment]
i'm having the same problem, and it didn't solve it by downloading an old version of spotify :(

**Comment by Einzigartigitsme** [comment]
I am using Spotify version 1.2.9.743.g85d9593d, have this same 'something went wrong' issue.
When I search for a song or album and click the album to open it, this appears; sometimes it works fine and sometimes it doesn't.
Everything is up to date according to me. 
so, I uninstalled this theme.
and I miss it.

**Comment by vu-kenny** [comment]
#26 - Removing the "move user profile icon to navbar" feature (codelines 265-271) fixed the issue for me :)

**Comment by vu-kenny** [comment]
I also found out that if you apply spicetify with devtools `spicetify apply enable-devtools` the error will still occur, but when you reload the client, it will reload to the intended destination. 
Without devtools enabled: the reload will always throw you back to the main page.

**Comment by TakiTakiS** [comment]
if anyone finds a way to fix this issue please walk me through getting it solved, **I'm stupid**. This is my favorite theme on Spicetify and I can't wait to use it properly without issues :D
![fuckthis](https://user-images.githubusercontent.com/132225540/235371095-471464c7-407e-485f-84e9-ed919c30e457.PNG)

**Comment by harbassan** [comment]
@TakiTakiS there is a temporary fix for the issue that would involve installing it locally, and removing lines 265-271 in the galaxy.js file. Otherwise Ill fix the issue properly soon.

**Comment by Einzigartigitsme** [comment]
> if anyone finds a way to fix this issue please walk me through getting it solved, **I'm stupid**. This is my favorite theme on Spicetify and I can't wait to use it properly without issues :D ![fuckthis](https://user-images.githubusercontent.com/132225540/235371095-471464c7-407e-485f-84e9-ed919c30e457.PNG)

Cheers! I'm stupid too.

**Comment by TakiTakiS** [comment]
is the issue officially fixed?? it works for me now I just tried it again 
it doesn't have the smth went wrong error anymore :D

**Comment by harbassan** [comment]
I think this issue should be fixed now, but ill leave this issue open in case its not for anyone.
