### ISSUE TITLE
Dropdown Submenus under PFP appear on the other side of screen

### ISSUE THREAD

**Issue by ProfLS** [harbassan/spicetify-galaxy#15]
I have attempted to reset all experiments, which didn't work.  I then reset the marketplace, and retried the theme, but it led to the same result.  Possibly resulting from the PFP being shifted to the left instead of it's default location on the right?  

![image](https://user-images.githubusercontent.com/43427862/219949194-e6800bae-4dd9-48a8-b7bf-0bf484e22649.png)

**Comment by harbassan** [comment]
Spotify version?

**Comment by ProfLS** [comment]
![image](https://user-images.githubusercontent.com/43427862/219991184-d6cde165-11ab-4e27-ba7e-a09c26c9e02c.png)

**Comment by harbassan** [comment]
yeah 1.2.5 is currently on a kinda "testing" phase where some users get changes and others dont, so I cant actually fix this until they fully push those changes out to everyone else. Solution for now is to downgrade your Spotify to the previous version, which should be working fine.

**Comment by ProfLS** [comment]
Sounds cool :) thanks!
