### ISSUE TITLE
Unexpected Padding in UI

### ISSUE THREAD

**Issue by metarex21** [harbassan/spicetify-galaxy#16]
Dear Dev. Is this expected?
![image](https://user-images.githubusercontent.com/72374116/219961166-abf74afb-cabd-46ed-b5b4-96e89b9f4b3e.png)

A fullscreen screenshot, if necessary⬇:
![image](https://user-images.githubusercontent.com/72374116/219961171-b3be0675-a85d-40e2-afb5-2143da9c7c4f.png)

**Comment by harbassan** [comment]
What spotify version are you on?

**Comment by harbassan** [comment]
Currently Spotify is pushing out certain changes to specific users as a sort of "testing", and I've got to actually wait till they push them to everyone else before I can fix things. For now the solution is to downgrade spotify, or you can just wait.
