### ISSUE TITLE
profile icon misaligned

### ISSUE THREAD

**Issue by plutozzzzza** [harbassan/spicetify-galaxy#19]
![Screenshot 2023-03-04 190901](https://user-images.githubusercontent.com/28511923/222934611-2a52b496-64ed-439a-a20a-7f619ee086da.png)

**Comment by plutozzzzza** [comment]
might just be me having this issue but its just a small detail that is so annoying

**Comment by harbassan** [comment]
What are your spotify and spicetify versions?

**Comment by plutozzzzza** [comment]
Spotify for Windows
1.2.6.863.ge7902f05
Spicetify v2.16.2
Theme: Galaxy / base
Extensions: galaxy.js
Custom apps: marketplace

**Comment by harbassan** [comment]
ok yeah i see the issue, ill fix it by a day or two

**Comment by plutozzzzza** [comment]
alright thanks

**Comment by harbassan** [comment]
Should be fixed with the latest version of the theme.
