### ISSUE TITLE
Frozen experimental features page and unable to see extension sub-options

### ISSUE THREAD

**Issue by Goodly58** [harbassan/spicetify-galaxy#2]
Spotify for Windows
1.1.99.878.g1e4ccc6e
Spicetify v2.14.3

![image](https://user-images.githubusercontent.com/63460148/203843440-b34dcba6-f653-45ad-b322-51e1c0c9c70f.png)
GoToSong and some plugins have sub-options that open on the left side, and since this theme places the profile picture on the left side (which is more aesthetically pleasing), the options can't be seen regardless of the window size/fullscreen. Is this to be changed from the extension config files itself?

![image](https://user-images.githubusercontent.com/63460148/203843592-cbd85a2a-2440-4ae8-86f6-7cb716ad73f0.png)
Experimental features page is frozen; you can't scroll up and down, only the search functionality can be used. This doesn't happen in SpicetifyDefault.

**Comment by harbassan** [comment]
Hey, both issues should be fixed as far as I can tell but it might take a little while for the marketplace version to update. Thanks for reporting these bugs, it really helps me as I wouldn't have noticed otherwise. Also, I appreciate the praise and I'm glad you like it!

**Comment by Goodly58** [comment]
Glad I could help in any way, your words meant a lot to me, thank you too :).
