### ISSUE TITLE
How can i remove this shadow on the bottom 

### ISSUE THREAD

**Issue by ZeeoTwo** [harbassan/spicetify-galaxy#20]
# this one
![image](https://user-images.githubusercontent.com/65177239/224188898-3c5b12c4-6f5a-48df-818d-051ed575d9f3.png)

## And
why i don't see your user.css in my theme folder, because if i could see it i'm 90% sure i could remove that gradient on my own

i installed your theme through marketplace, should i do it manually?
btw this is what i get in marketplace with your theme (like a lot of invalid css idk if it's common but ig it's not)
![image](https://user-images.githubusercontent.com/65177239/224189219-aff3bd1e-61b5-495d-ae82-46b6eb34e30f.png)

### info

Spotify for Windows
1.2.6.863.ge7902f05
Spicetify v2.16.2
Theme: Galaxy / base
Extensions: volumePercentageWrapper.js, playlist-icons.js, romaji_lyrics.js, fixEnhance.js, romaji-convert.js, romaja_lyrics.js, fullAppDisplayMod.js, galaxy.js
Custom apps: new-releases, lyrics-plus, marketplace

**Comment by ZeeoTwo** [comment]
Found it:
```
.bg-main-shadow {
  /* background: linear-gradient(rgba(0, 0, 0, 0.196) 203px, rgba(0, 0, 0, 0.518) 474px, rgba(0, 0, 0, 0.596) 700px) !important; */
  position: absolute;
  width: 100%;
  height: 100%;
}
```

**Comment by harbassan** [comment]
Yeah that invalid css thing is just a marketplace related issue
