### ISSUE TITLE
It keep changing the background in lyrics tab even applying the bg everywhere

### ISSUE THREAD

**Issue by Aiz4u** [harbassan/spicetify-galaxy#21]
![image](https://user-images.githubusercontent.com/127457560/224194533-cce4b2cc-d900-4294-ade9-7393fc811acc.png)
![image](https://user-images.githubusercontent.com/127457560/224194554-8f79987b-8dd9-43ad-b15c-5259e1e360f8.png)

**Comment by harbassan** [comment]
make sure you have the latest version of the theme.
