### ISSUE TITLE
background still switching to song image 

### ISSUE THREAD

**Issue by plutozzzzza** [harbassan/spicetify-galaxy#24]
![image](https://user-images.githubusercontent.com/28511923/230514007-98f03276-387c-4370-8562-907ffbd7de9a.png)
![image](https://user-images.githubusercontent.com/28511923/230514033-71e70f1b-ed12-45b7-890f-fbdf1d5cd422.png)
supposed to be all black background but it keeps switching to the song image
Spotify for Windows
1.2.7.1277.g2b3ce637
Spicetify v2.16.2

**Comment by harbassan** [comment]
update spicetify maybe?

**Comment by fuiafnwiua** [comment]
> update spicetify maybe? Is the issue only occuring on the liked songs page or is it on every page?

It happens to my too, I'm pretty sure both spice and spotify are updates. Not sure why it does it but every time you press the lyrics button or switch playlist it goes back to normal.

**Comment by fuiafnwiua** [comment]
It's everytime you play a song it resets back to album cover

**Comment by harbassan** [comment]
should be fixed. if you're using a marketplace install wait a couple hours for it to update.

**Comment by plutozzzzza** [comment]
working now, thanks
