### ISSUE TITLE
I want to be only on the playlist page, album page and artist(No Background) page. Add div elements, and can follow and scroll

### ISSUE THREAD

**Issue by youthyan** [harbassan/spicetify-galaxy#27]
I want to modify this js code, 
I want to be only on the playlist page, album page and artist(No Background) page.
Add element <div><bg-main-container> to this .main-entityHeader-image tag,
Use the newly created image as the shadow background,
I don't know how to modify the code to run normally without error

The following is the wrong code, 
I don’t know how to modify it, 
I really like the theme you made, can you help me, thank you very much.

**Comment by youthyan** [comment]
const bgImage = bgContainer.children[0].children[0];
const bgShadow= document.querySelector(".main-entityHeader-image");
bgShadow.prepend(bgContainer);


Here the css selector reports an error, because some pages do not have this element, 
I just want to add it to the playlist, album and artist pages, 
how should I modify it, 
I am a beginner in js, can you help me, 
thank you very much.

**Comment by youthyan** [comment]
I just like music very much, I want to div my own player, I want to make it look good,thank you.

**Comment by harbassan** [comment]
Can you explain specifically what you want to do without mentioning the code, then I can help you. Do you want to change the background image? If yes, what exactly do you want to change it to?

**Comment by youthyan** [comment]
<img width="332" alt="截屏2023-05-01 下午12 26 14" src="https://user-images.githubusercontent.com/105373147/235408793-7355d01a-48ce-4901-838b-53e20b0ed8a3.png">
<img width="333" alt="截屏2023-05-01 下午12 24 57" src="https://user-images.githubusercontent.com/105373147/235408807-1f01a9e6-fa33-4d6b-ab18-a93edf5522ee.png">
<img width="774" alt="截屏2023-05-01 下午12 45 28" src="https://user-images.githubusercontent.com/105373147/23540882
<img width="649" alt="截屏2023-05-01 下午12 48 00" src="https://user-images.githubusercontent.com/105373147/235408833-168f5688-72a9-4fc1-8227-3aca506c7deb.png">
0-b57f769d-6428-445d-9e8e-0aae283329d1.png">

<img width="744" alt="截屏2023-05-01 下午12 45 41" src="https://user-images.githubusercontent.com/105373147/235408828-29eff99f-e712-49c7-b442-ce3f08722c52.png">


I just want to add a repeated image to this image container as a background shadow that can follow the scrolling.
 I think it will be cooler and better than the box-shadow property. It's exciting. 

I can modify the css to make it look good. 
But I don't know how to modify js, and I can't add a repeated image to the image container.

**Comment by youthyan** [comment]
I just want to add createElement("div") to the image container, not to the body background, sorry, I fell asleep, the time zone is different

**Comment by youthyan** [comment]
I think you may not understand what I want to do. 
I didn't want to change the background. 
I just want to put the background in the image container. 
Although there will be two identical images in the image container, this is what I want to do.

**Comment by harbassan** [comment]
If you only want it to happen for those specific pages, then you need to run your created function on page change when the page type is any of those three. You can do this by adding your function to this part of the galaxy.js file like so:
```javascript 
switch (type) {
        case "playlist":
          getPlaylistImage(uid);
          myFunction()
          break;
        case "album":
          fetchAlbumImage(uid);
          myFunction()
          break;
        case "artist":
          fetchArtistImage(uid);
          myFunction()
          break;
```

Then in your function you need to wait for the `.main-entityHeader-image` by using the `waitForElement()` function that is in the code already. You can see how it is used in the code. 

Then inside the callback function of that you can create your image element and set the source of it to the `.src` of the `.main-entityHeader-image` that you have waited for.

Can you understand this?

**Comment by youthyan** [comment]
I found out that I can't write functions. He doesn't work at all, tried for a long time, still doesn't work. I just learned a little js. I can understand the meaning of these functions through ChatGPT, but I can't write a complete and accurate function now.

function myFunction(){
  waitForElement([".main-entityHeader-image"], ([image2]) => {
     const bgs = document.createElement("div");
     bgs.className = "bg-main-container";
     bgs.innerHTML = `</div><div class="bg-image-container"><img class="bg-main-image"></div><div class="bg-main-shadow">`;
     const bgImage = bgs.children[0].children[0];
     const imgHeader = image2.parentElement;
     imgHeader.prepend(bgs);
  });
}

 Spicetify.Platform.History.listen(({ pathname }) => {
    const [, type, uid] = pathname.split("/");
    //  change background images for certain pages
    if (!config.useHomeEverywhere) {
      switch (type) {
        case "playlist":
          getPlaylistImage(uid);
          myFunction();
          break;
        case "album":
          fetchAlbumImage(uid);
          myFunction();
          break;
        case "artist":
          fetchArtistImage(uid);
          myFunction();
          break;
        case "lyrics":
          fetchCurrTrackAlbumImage();
      }
      if (pathname === "/collection/tracks") fetchCurrTrackAlbumImage();
    }

**Comment by youthyan** [comment]
1. I don't know how to write **"myFunction()"** to make it work.
    - If I put **waitForElement([".main-entityHeader-image"], ([image2]) =>** 
    Outside of **"myFunction()"** ,
    - it will only work on **Reload**, and switch pages doesn't work.

3. I don't know how to set source **image src** for **.main-entityHeader-image**.
    - If I put **const bgImage = bgs.children[0].children[0]**; 
    in a function,
    - **function setBg(imagedata) {
               bgImage.src = image data; }** 
will be wrong.

I don’t seem to understand the basics of js.
I understand js code in order to modify this js. But js is so difficult. 
So please help me modify it, thank you very much.

**Comment by harbassan** [comment]
this is the function:
```javascript
const myfunction = () => {
        setTimeout(() => {
            waitForElement([`.main-entityHeader-image`], ([headerImage]) => {
                const shadowImage = headerImage.cloneNode(true);
                headerImage.parentElement.append(shadowImage);
            });
        }, 50);
};
```
then this is the call:
```javascript
if (!config.useHomeEverywhere) {
            switch (type) {
                case "playlist":
                    getPlaylistImage(uid);
                    myfunction();
                    break;
                case "album":
                    fetchAlbumImage(uid);
                    myfunction();
                    break;
                case "artist":
                    fetchArtistImage(uid);
                    myfunction();
                    break;
                case "lyrics":
                    fetchCurrTrackAlbumImage();
}
```

I recommend you learn javascript if you want to do more, but you should be able to use css from here to get to your desired result.

**Comment by youthyan** [comment]
This function is fine, the method of clone is very good.
I will modify the css, you are **amazing**.
I have solved this problem, thank you for your patience and guidance.
