### ISSUE TITLE
Question about licencing

### ISSUE THREAD

**Issue by Motschen** [harbassan/spicetify-galaxy#28]
Hey, I'm the creator of the [Retroblur](https://github.com/Motschen/Retroblur) spicetify theme and I was wondering if I could implement a modified version of your background image switcher code in my theme, giving credits to you of course.
Due to your theme not having a licence, I'm assuming it's All Rights Reserved, so it would be very nice if you gave me permission to use that part of your code in my MIT licenced theme.

**Comment by harbassan** [comment]
Yeah sure, that's all good with me.

**Comment by harbassan** [comment]
But apart from that i would appreciate it if you made an effort to keep our two themes distinct, as since you recently updated it they look pretty similar apart from the blur.

**Comment by Motschen** [comment]
Thank you very much for letting me use your code :)
I think there's still a big visual difference between our themes, as mine is very vibrant and colorful, as well as being a bit more faithful to the original spotify style, while yours is darker and more uniquely stylized.
