### ISSUE TITLE
Unable to use UI elements

### ISSUE THREAD

**Issue by metarex21** [harbassan/spicetify-galaxy#3]
Spotify for Windows
1.1.99.878.g1e4ccc6e
Spicetify v2.14.3
(installed from Spicetify Marketplace)
The marked UI buttons are unresponsive (don't register clicks)
![Screenshot 2022-11-27 133216](https://user-images.githubusercontent.com/72374116/204125434-ab5f86da-0f15-404e-b2e6-0c97dc7eef41.png)
Thanks in Advance!

**Comment by harbassan** [comment]
Did you figure it out?

**Comment by metarex21** [comment]
> Did you figure it out?
I was using SpotX earlier. Maybe it was conflicting with the Extension/Theme. Reinstalling Spotify from the official website did the job!
