### ISSUE TITLE
Some of the title of the song covers the album cover

### ISSUE THREAD

**Issue by reinperiodpooh** [harbassan/spicetify-galaxy#31]
I use a rotating cover art snippet and when i opened spotify, this suddenly happened.
 I tried removing the theme, reinstalling it, No luck.
 I tried removing the extension, still no luck.
 
 Is there a way to fix this?

<img width="290" alt="Screenshot 2023-05-19 at 21 37 09" src="https://github.com/harbassan/spicetify-galaxy/assets/134077957/c1a5525c-3905-4f81-a413-880f96510fe7">
<img width="1436" alt="Screenshot 2023-05-19 at 21 35 50" src="https://github.com/harbassan/spicetify-galaxy/assets/134077957/e2599e70-f995-43fb-8713-1309b5bc5055">
<img width="278" alt="Screenshot 2023-05-19 at 21 37 28" src="https://github.com/harbassan/spicetify-galaxy/assets/134077957/994945ab-be35-4fda-825b-f2496d6aacde">
<img width="1434" alt="Screenshot 2023-05-19 at 21 37 35" src="https://github.com/harbassan/spicetify-galaxy/assets/134077957/ca31549b-7c82-4244-86a5-5a313f568379">

**Comment by harbassan** [comment]
ill fix this soon when I update for the new spotify layout, shouldn't be too long.

**Comment by harbassan** [comment]
should be fixed now, give it a couple of hours or so to update on the marketplace.
