### ISSUE TITLE
the artist and song name get cut out to the side

### ISSUE THREAD

**Issue by zlodeo** [harbassan/spicetify-galaxy#32]
![image](https://github.com/harbassan/spicetify-galaxy/assets/134113721/4ad8f01f-faee-40a7-a401-65d3d595d788)

**Comment by harbassan** [comment]
ill fix this soon when I update for the new spotify layout, shouldn't be too long.

**Comment by harbassan** [comment]
should be fixed now, give it a couple of hours or so to update on the marketplace.
