### ISSUE TITLE
Powershell doesnt recognize theme

### ISSUE THREAD

**Issue by williwoo** [harbassan/spicetify-galaxy#35]
I'm new to github and not really sure what im doing, but i cloned the repo and created files on my desktop, then followed your steps. After running the commands in powershell, there is an error 'Theme "Galaxy" not found' I've had the theme installed from the marketplace, but it doesn't look like it does in your images, so i figured i should try installing through powershell.
![image](https://github.com/harbassan/spicetify-galaxy/assets/134835987/43215c27-9a61-4a57-946b-b87c24f02d76)

Please help :)

**Comment by harbassan** [comment]
currently the reason it doesnt look as it should is because it needs to be updated, im nearly finished with it tho so it should be done by tommorow.

**Comment by williwoo** [comment]
> 

its just the side and song bars are opaque and in ur pics theyre transparent, thanks for fixing it tho!

**Comment by harbassan** [comment]
should be fixed now, give it a couple of hours or so to update on the marketplace.
