### ISSUE TITLE
 bad optimization

### ISSUE THREAD

**Issue by guztax** [harbassan/spicetify-galaxy#37]
When you enter the cover of the album, there is a drastic FPS drop on Spotify, and at several other times this problem also occurs

Prints of the places where you can notice the fps drop:
![image](https://github.com/harbassan/spicetify-galaxy/assets/108374911/cfa96d1f-a092-4fe7-a95c-5c64122560d5)
![image](https://github.com/harbassan/spicetify-galaxy/assets/108374911/08b1db80-367f-4b6b-a7a4-4d99aa8cea5a)
![image](https://github.com/harbassan/spicetify-galaxy/assets/108374911/053517e9-4c0f-4c4d-81ad-d5512444bbcb)

**Comment by harbassan** [comment]
the fps drop is probably because of either just the image loading (its pretty high quality) or the css gradient effects. Ill try to make an option to remove those effects to increase the performance soon, but I dont think theres a way to keep them while also imporoving performance.

**Comment by guztax** [comment]
ok, thank you
Your theme turned out very nice, congratulations for the work
