### ISSUE TITLE
black background and no option to change the background 

### ISSUE THREAD

**Issue by man8000** [harbassan/spicetify-galaxy#39]
spicetify updated and now the theme has a black background and removed the option to change the background

**Comment by man8000** [comment]
spicetify updated and now the theme has a black background and removed  the option to change the background

**Comment by Imaginarysilk** [comment]
Same thing happened to me. Been trying everything to fix it for an hour and a half, but nothing worked. Pretty much gave up at this point and hoping the creator fixes it.

**Comment by DawarTheDastardly** [comment]
same issue here as well, hopefully it gets fixed soon enough

**Comment by harbassan** [comment]
yep was just a silly mistake of not renaming a file, should be fixed now once it updates

**Comment by DawarTheDastardly** [comment]
thank you

**Comment by 7eeo** [comment]
I still have the problem, how do I fix it?

**Comment by DawarTheDastardly** [comment]
try uninstalling and reinstalling the theme, it worked for me.
