### ISSUE TITLE
[Feature Request] Automatically change home screen background according to the now playing artist/song/album

### ISSUE THREAD

**Issue by Satanarious** [harbassan/spicetify-galaxy#4]
An option which can be enabled to automatically change the home screen background to that of the currently playing:
- Artist
- Song
- Album

I used to use musicbee before I started using Spotify and it used to fetch what I earlier mentioned using APIs and display as the background art. I think it would be an awesome feature if it could be integrated into this theme. There are quite a few sources to fetch these images from.

Love the theme btw, always wanted something like this.

**Comment by harbassan** [comment]
I've added the option to use the currently playing song, you can access it in the home edit settings. I might add an option to use the artist image later as well. Might take a while before it updates on marketplace.

**Comment by harbassan** [comment]
If you installed it through marketplace it'll take max 1 day and will happen automatically. Obviously if you installed it manually you can just download the new files.

**Comment by Satanarious** [comment]
Are you fetching the now-playing song/artist art from Spotify? Because the quality is not suitable for a background. I was wondering if you could use multiple sources to fetch the background, like:
- [last.fm](https://www.last.fm/)
- [gettyimages](https://www.gettyimages.in/)
- [Deezer API](https://developers.deezer.com/)
- [Bing Image Search API](https://www.microsoft.com/en-us/bing/apis/bing-image-search-api)
- [Fantart.tv](https://fanart.tv/music-fanart/)

**Comment by harbassan** [comment]
The best I could find for album art was 1000x1000px using the deezer api, vs 600x600px from Spotify. Also, for artist images fanart.tv is the only one I can find with hq images, but it doesnt have images for a lot of artists. If you can find something with better quality let me know.

**Comment by harbassan** [comment]
Unfortunately the free versions of both are too limited.
