### ISSUE TITLE
Cant use the hover panels snippet

### ISSUE THREAD

**Issue by Ansh3962** [harbassan/spicetify-galaxy#41]
i cant use the hover panels snippet. Its not showing for some reason but the albums are there as i can read the album names when i put my cursor over them but i cant actually see them

**Comment by harbassan** [comment]
does it work on other themes?

**Comment by Ansh3962** [comment]
yes

**Comment by harbassan** [comment]
i tested it and it seems that hover panels is broken, has nothing to do with the theme.
