### ISSUE TITLE
Theme broke on the new spotify update

### ISSUE THREAD

**Issue by Satanarious** [harbassan/spicetify-galaxy#43]
Just updated to:
- Spotify for Windows (32 bit)
  - 1.2.14.1149.ga3ae422d
- Spicetify v2.20.1

They made the Library X thing a permanent in this one, and the theme seems broken, left sidebar is all black and there's a gap between the topbar and the sidebars.
![image](https://github.com/harbassan/spicetify-galaxy/assets/42642682/cc0a42e2-7d00-4d5c-85bd-189739cd2f51)

Works fine on till v1.2.13.661.ga588f749 of spotify.

**Comment by harbassan** [comment]
updated it now
