### ISSUE TITLE
newby here, not sure how to change colors

### ISSUE THREAD

**Issue by REALtony4twenty** [harbassan/spicetify-galaxy#44]
I used the 1 click install through marketplace. I was able to change background image fine using the edit on the home screen. However I would like to change the colors and GUI as well. It says "Go into your theme folder and open either: color.ini or user.css" however, I can only find files likes these in "roaming" and "local" and I only see default stuff and adding a "[base] with color changes" to the default one had no luck. thanks for any help!

**Comment by harbassan** [comment]
That only applies for a local install, for the marketplace install you would go into the theme devtools button (looks like a paintbrush and is next to the marketplace search) and edit the color.ini in there. Hope thats helpful.

**Comment by REALtony4twenty** [comment]
thats huge, I wasnt aware there was one. Just had to toggle the "theme developer tools" in the setting menu and was able to edit. Thankyou so much!
