### ISSUE TITLE
Im so confused..

### ISSUE THREAD

**Issue by CarMaster007** [harbassan/spicetify-galaxy#46]
so i dont have a .spicetify folder? theres only spicetify-themes-master which is in downloads. and there are multiple user.css and color.ini folders. idk i might be stupid im new to all of this stuff so please help!

**Comment by harbassan** [comment]
if you want an easier way to manage the themes and extensions I would suggest using spicetify marketplace. Otherwise, you can find the .spicetify folder by using this guide: https://spicetify.app/docs/advanced-usage/extensions, and then just move the theme folder into the Themes folder in here.
