### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by QuinnOlsson** [harbassan/spicetify-galaxy#48]
Followed the instructions in the readme, and after completing the steps, I do not see the edit button at the top left, nor do any playlists have the album image as a background.

Got a few questions. The file extension.js that goes in the extensions folder of /.spicetify, is that a file that is in this repo or is it a file we need to create? Cause if you simply add a file called extension.js then run the command `spicetify config extensions galaxy.js` and then `spicetify apply` spicetify throws an error about galaxy.js not existing.

I tried creating a galaxy.js file in extensions, and put the code from theme.js (the only js file I could find in your repo, if this is the wrong file please lmk). Is there an extension.js file somewhere in the repo that I overlooked?

**Comment by harbassan** [comment]
sorry, i mightve forgotten to update the redme but you no longer need to use the extension.js due to a spicetify update, jus put everything into the themes folder and itll work.
