### ISSUE TITLE
No issues, absolutely great theme. Just some questions.

### ISSUE THREAD

**Issue by leofeik2909** [harbassan/spicetify-galaxy#49]
Is there a way to change the text's colors? and what are the dimensions of the backgrounds to be properly displayed? (sometimes pictures get cropped)

**Comment by harbassan** [comment]
yes, download the theme locally and edit the color.ini file. The dimensions are whatever the size of your spotify window is, so if you keep it fullscreen it would be 1920x1080 aspect ratio or whatever your screen size is.
