### ISSUE TITLE
Make more space for the title and the underlying text

### ISSUE THREAD

**Issue by Satanarious** [harbassan/spicetify-galaxy#5]
Currently the 'Save to Library' button hides most of the content of the title info text and the underlying text as well. It would be great to have the playback controls on top of the seekbar to make space for the text and shift the 'Save to Library' button to the right next to the seekbar.

![Screenshot](https://user-images.githubusercontent.com/42642682/206334035-749d53e4-a01c-4f76-ad3b-6ac6c030c85a.png)

**Comment by harbassan** [comment]
I'm not sure why the song info is squashed into the corner there, as it should extend all the way to the shuffle button. 
![image](https://user-images.githubusercontent.com/84175605/207213153-f2f2e1ea-5740-4e24-a299-30348ea935d4.png)

I'll see if i can figure out why its doing that.
