### ISSUE TITLE
problem in the menu when clicked on profile picture

### ISSUE THREAD

**Issue by Aeropro4** [harbassan/spicetify-galaxy#51]
Can ya do something about this 
![image](https://github.com/harbassan/spicetify-galaxy/assets/113044496/d053aee6-1c2f-4819-bde2-9d32fb47362c)
The extensions menu is going out of screen
and the profile picture is under the close button

**Comment by Aeropro4** [comment]
pls reply if it can be fixed or not

**Comment by harbassan** [comment]
yeah ill see what i can do tommorow

**Comment by Aeropro4** [comment]
> yeah ill see what i can do tommorow

K thx

**Comment by harbassan** [comment]
I fixed it, should update soon.

**Comment by Aeropro4** [comment]
K thx
