### ISSUE TITLE
Top marketplace layout broken

### ISSUE THREAD

**Issue by Syycorax** [harbassan/spicetify-galaxy#54]
As you can see below, the top of the marketplace is overlaying itself, and the search button disappeared
![image](https://github.com/harbassan/spicetify-galaxy/assets/54723548/4896b3b8-5648-4a07-b7ea-db88fe87bf24)
On another note, you should remove the extension part on the README, it's quite confusing (I've seen in #48 that the step is not necessary anymore)

**Comment by harbassan** [comment]
haven't updated the theme in a while, so ill get around to fixing this along with everything else soon.
