### ISSUE TITLE
Like heart button displacement

### ISSUE THREAD

**Issue by Aeropro4** [harbassan/spicetify-galaxy#58]
umm idk if i have installed some extension or the theme but pls review
![image](https://github.com/harbassan/spicetify-galaxy/assets/113044496/bf665fb8-048e-4ce4-bddb-f0ae646ada68)

**Comment by harbassan** [comment]
The search page no longer looks like this anymore so im assuming this issue is fixed?

**Comment by Aeropro4** [comment]
yeah its fixed!
