### ISSUE TITLE
Wierd floating box

### ISSUE THREAD

**Issue by greneboy** [harbassan/spicetify-galaxy#62]
![wierd_boxes_cards_spicetify](https://github.com/harbassan/spicetify-galaxy/assets/113216238/0fc442f5-5743-4968-953e-fd0f61299b83)
I just realized, what are these boxes? shadow-box? Ive search the element styles properties on user.css and the DevTools and haven't found the culprit yet.

**Comment by greneboy** [comment]
wait nvm I figured out how to fix it, just remove this lines somewhere on `MAIN VIEW`.

```
.main-card-imageContainer .main-cardImage-imageWrapper::after {
     content: "";
     position: absolute;
     top: 0;
     bottom: 0;
     left: 0;
     right: 0;
     background: rgba(255, 255, 255, 0.1);
     transform: rotate(45deg) translate(0px, -90%);
     transition: all 0.3s ease-out;
     filter: blur(4px);
}
.main-card-card:hover .main-card-imageContainer .main-cardImage-imageWrapper::after {
     transform: rotate(45deg) translate(0px, -70%);
     filter: blur(6px);
}
```

**Comment by Phntomm** [comment]
wait so i dont really understand how did u fixed that? cuz im facing a similar issue 
![Ca44pture](https://github.com/harbassan/spicetify-galaxy/assets/169238070/99fe6fb7-ed89-4cad-9a15-362036c42b83)
![Cap22ture](https://github.com/harbassan/spicetify-galaxy/assets/169238070/bad6bbf6-3030-45e7-a1ec-b9976bd1607e)
