### ISSUE TITLE
The album title and artist name titles have insufficient line height, resulting in incomplete display of Chinese or Japanese titles.

### ISSUE THREAD

**Issue by Nirnturt** [harbassan/spicetify-galaxy#68]
The line height for the album title and artist name appears to be too conservative. The current line height of 56px may result in incomplete display of the top portions of Chinese and Japanese characters. After some customization, a line height of 66px seems to be a better choice. Of course, you can also find a more elegant solution to this issue.

![1cf5883d73859a3ee6c81afb81b5280](https://github.com/harbassan/spicetify-galaxy/assets/26437323/60fd2728-e896-4834-9394-19cccb3542b4)
![0a8171760b528134d2d50bcd2c2d9cb](https://github.com/harbassan/spicetify-galaxy/assets/26437323/9eef8560-45b6-4191-8cfb-7d1c81f3234b)

after repair
![5ccc8e8e0f2b48484493b8e0a5f2b4b](https://github.com/harbassan/spicetify-galaxy/assets/26437323/21732d7c-2cb0-45d8-a3df-1835a71a2e53)
![06cc901f02836f3d66bde8341e794d7](https://github.com/harbassan/spicetify-galaxy/assets/26437323/3b22469d-7f97-4c9f-93bb-a6d246c66257)

Thank you very much for your work. Galaxy is definitely the coolest theme for Spicetify 👍

**Comment by harbassan** [comment]
i've just fixed this, should update soon on marketplace.
