### ISSUE TITLE
[Feature Request] Disabling Wallpaper changes

### ISSUE THREAD

**Issue by Barocena** [harbassan/spicetify-galaxy#7]
I like the layout and design of theme but I rather not change my wallpaper for each playlist,song etc..
so an option to keep the main page wallpaper everywhere would be great

**Comment by harbassan** [comment]
ill work on it

**Comment by harbassan** [comment]
might take a while to update but the option should be there now. thanks.

**Comment by harbassan** [comment]
let me know if its working as you wanted it to.

**Comment by Barocena** [comment]
there are few issues,
- options are not applying without rebooting spotify (both option have the same issue) 
- wallpaper still changes on artist pages
- wallpaper changes to current song when both `use currentplaying song as home bg` and `use the home bg everywhere` options enabled

**Comment by harbassan** [comment]
Those last two were on purpose. Do you want the image you set as the home background to be everywhere except the home page, which will have the currently playing song?

**Comment by harbassan** [comment]
cant you just toggle off the current song option?
