### ISSUE TITLE
Default spotify gradient peeking through

### ISSUE THREAD

**Issue by Hrushal-Nikhare** [harbassan/spicetify-galaxy#71]
![image](https://github.com/harbassan/spicetify-galaxy/assets/82302201/f3bcdb3b-fc5f-4513-9932-78095e0527b8)

and the color stays on scroll 

![image](https://github.com/harbassan/spicetify-galaxy/assets/82302201/4c86f24c-62d0-40a7-ba8c-1da3c34390d6)

**Comment by Hrushal-Nikhare** [comment]
`#main > div.Root > div.Root__top-container > div.Root__main-view > div.main-view-container > div.main-view-container__scroll-node > div:nth-child(2) > div.main-view-container__scroll-node-child > main > div.S4OmZ_IZexmZ5dasPqW5` 

is the div that is responsible for the color

**Comment by Hrushal-Nikhare** [comment]
found a fix
```css
div.S4OmZ_IZexmZ5dasPqW5 {
  display: none;
}
```

**Comment by harbassan** [comment]
if you've already found the fix, make a pr!

**Comment by Hrushal-Nikhare** [comment]
The glitch seems to be fixed in the new update but the sticky nav didnt get mapped i think
![image](https://github.com/harbassan/spicetify-galaxy/assets/82302201/a4d835c1-a533-4211-9272-b95111a03395)

**Comment by Hrushal-Nikhare** [comment]
the latest spicetify update has fixed the mappings so closing
