### ISSUE TITLE
Task bar unable to be use ( cant move application location)

### ISSUE THREAD

**Issue by BeastBalak** [harbassan/spicetify-galaxy#76]
i have 2 monitors and the theme makes it impossible to move the app location by touching task bar ( the top area with minimize close etc) and idk if theres alternatives to move it between monitors but please make the taskbar thicker so its much easier to use

**Comment by BeastBalak** [comment]
https://github.com/harbassan/spicetify-galaxy/assets/169268061/19a62b0d-a0d3-49f7-a7dd-22540b2b43b1

This video sums up the issue and shows the problem and its fix

**Comment by Phntomm** [comment]
btw i see ur also facing the same theme issue as mine 
do yk any fix to that? 
![Ca44pture](https://github.com/harbassan/spicetify-galaxy/assets/169238070/3eb1a60c-9383-4dda-a563-6ef0e79202d7)
![Cap22ture](https://github.com/harbassan/spicetify-galaxy/assets/169238070/968502e6-c6d0-4029-81ca-15339230ece8)
these weird bars and floating shape type thing

**Comment by BeastBalak** [comment]
> btw i see ur also facing the same theme issue as mine do yk any fix to that? ![Ca44pture](https://private-user-images.githubusercontent.com/169238070/328968296-3eb1a60c-9383-4dda-a563-6ef0e79202d7.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDMyNTgsIm5iZiI6MTcxNTI0Mjk1OCwicGF0aCI6Ii8xNjkyMzgwNzAvMzI4OTY4Mjk2LTNlYjFhNjBjLTkzODMtNGRkYS1hNTYzLTZlZjBlNzkyMDJkNy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQwODIyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTExZjhjZDY1OWE2MjdjZDhlYjk2NzI0NWIxMDc5N2I4ZTNjMTM0NWRiN2JiNDcyYWE0MDMxMGYxZDkyOWI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9s1HB_jA7qijE9v0zeR4s-rRUvZIfVq5-M8X6FNjodg) ![Cap22ture](https://private-user-images.githubusercontent.com/169238070/328968375-968502e6-c6d0-4029-81ca-15339230ece8.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDMyNTgsIm5iZiI6MTcxNTI0Mjk1OCwicGF0aCI6Ii8xNjkyMzgwNzAvMzI4OTY4Mzc1LTk2ODUwMmU2LWM2ZDAtNDAyOS04MWNhLTE1MzM5MjMwZWNlOC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQwODIyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2I5MmIxMjAyYWEzOGRkYTMzYTZhNzUzNzBjOTUwZTkwMjQ3Y2MzNmFhMGE2MDVlYmMyY2RlYmQ4MTVlMDQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3qoC2aU0DIXKF1J3oyc1lWWEHQyJE_xZrzc170xEo_c) these weird bars and floating shape type thing

I think they're new spotify "Feature" its to basically scroll through artist or playlist or smth someone will prob make a extension to remove it soon so ig u gotta wait till that

**Comment by BeastBalak** [comment]
also if you wanna switch between monitors you can use shift + win key + arrow keys

**Comment by Phntomm** [comment]
yeah you are right its a scroll bar but i think its pretty annoying and useless. let me know if u find any fix to remove that
also thanks man for the switching monitor solution

**Comment by harbassan** [comment]
fixed in latest, give it some time to update in marketplace.
