### ISSUE TITLE
choose background image not working.

### ISSUE THREAD

**Issue by Nerxxy** [harbassan/spicetify-galaxy#89]
As title says when i choose a background the image i chose doesnt show up, its only showing the default image.

edit: using a link works tho for some reason, which is not ideal since a lot of my images are on my computer ):

**Comment by Satanarious** [comment]
It works explicitly for web links and not local paths. Just upload your local files to a file or image hosting service like [catbox](https://catbox.moe/) or [imgur](https://imgur.com/upload) and you should be good to go.

**Comment by Nerxxy** [comment]
ah ok thanks for the info, ill just use github to host them 👍
